### ISSUE TITLE
Add new member to the CNERG website

### ISSUE THREAD

**Issue by bam241** [cnerg/cnerg.github.com#140]
Add yourself to the CNERG website
-----------------------------------

1. Create a github account, if you don’t already have one.
2. Fork the CNERG website repository. This can be done by clicking the “Fork” button in the top-right corner. Forking means you have your own version of the repository where you can make changes that won’t be reflected in the main repository.
3. Clone your fork. This will download your fork to a directory on your local machine.
`git clone https://github.com/<github_username>/cnerg.github.com`
If you don’t have git on your machine, you can get it with
`sudo apt-get install git`
4. Create a new branch where you will make the changes. (It doesn’t have to be called “add_myself”, that’s just an example.)
`git branch add_myself`
5. Switch to your new branch.
`git checkout add_myself`
Note that steps 4 and 5 can be completed simultaneously with
`git checkout -b add_myself`
6.Descend into the directory where the source markdown (`*.md`) files for staff and students are located.
`cd community/people`
7. Create a new directory which will contain all data related to you.  You can name it how you like, but most are based on initials.
`mkdir <my_initials>` (replace `<my_initials>` with your initials)
8. Go to your new directory
`cd <my_initials>`
9. Create a new markdown file, `index.md`, which will be your personal page. It is probably a good idea to use someone else’s markdown file as a template. Your personal page should contain your name, contact information, research interests and/or projects being worked on, and education.
10. Upload a picture of yourself.
11. Add yourself to the database of people in `_data/people.yml`. This file currently has different sublists of people based on their role in CNERG.  Each entry should include a `name`, `url` - this is the directory that you created, e.g. `<my_initals>`, `image` - this is the image that will be used on the page of all group members, and `role` - this is your title and or description of  your role in CNERG.
12. Consult `README.md` to test locally
13. Once you feel it looks correct and the way you want it, add and commit your changes. This will save your changes to your local clone of your fork.
`git add <new_or_modified_files>`
`git commit -m “Added <my_name>”`
14. It is often very useful to use git status, which will give you information like which files have been modified but are not staged for commit, which files have been modified and have been staged for commit (i.e. they have been git added), and whether you have commits in your clone that are not yet reflected in your github fork or vice versa.
Push your new branch to your github fork.
`git push -u origin add_myself`
If your fork already contains the branch and you are only updating it with new commits, then git push by itself is sufficient.
15. Create a pull request (PR) between the branch on your fork and the `main` branch in the main repo. This can be done by using a web browser to navigate to your new branch on your fork and clicking “Pull request”. This will allow other users to review the changes you made and make comments, request changes, or approve your changes. Once your PR has been created, you should be able to see it here.
16. Once you and one or more reviewers are satisfied with your changes, someone with write access will merge your branch into the main repo. 
17. Once this is done, you’ll be able to find yourself on the staff and students page of the website

**Comment by bam241** [comment]
(this is a some test, to see how to link this with some project management tool...)

**Comment by lewisgross1296** [comment]
This is good information. I'm not sure how @gonuke is instructing new members to add themselves (and if this issue is being referenced). Perhaps the above steps could go into a `README.md` under `cnerg.github.com/community`. I could make a PR to do this that closes this issue if desired

**Comment by MicahGale** [comment]
My two cents:

1. This seems to be copy-pasted from a Google doc that @gonuke uses with the slack onboarding bot.
2. This has been stale for 4 years, and seems to be a [test] issue.
3. If this were memorialized in a wiki in the repo; it's too verbose IMO. This is meant as a teaching tool for people who are new to git. It does its job well. I don't think a git repo is the place to store such specific guidance on how to commit, etc. This would require some base skill to get to and read, and runs the risk of having stale information (e.g., IIRC the behavior of `git checkout` will change eventually). In general a guide in a README should be more about what to do and not how to do it.

This is all to say: let's just close this issue.

**Comment by MicahGale** [comment]
I'm just going for it and seeing if we need to reopen.

**Comment by lewisgross1296** [comment]
I was going to close it after finding out if the information is given to new students elsewhere, which you've let us know! I'm good with this remaining closed and not being added into the repo as a README.md
