### ISSUE TITLE
Implement FullCalendar Plugin for Events Page

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [cnerg/cnerg.github.com#234]
## Description
The events page on the Computational Nuclear Engineering Research Group (CNERG) website is currently under development. It could benefit from enhancements to improve its functionality and user experience. This issue proposes implementing the FullCalendar plugin to display events effectively.

I would like to express my sincere gratitude to the entire team for your invaluable contribution to the open-source community by making the CNERG website available as an open-source project. The resources and source code provided on your website have been immensely helpful in the development of [NukeHub](https://nukehub.org), and I cannot thank you enough for this.

## Proposed Changes
- Integrate the FullCalendar plugin into the events page.
- Utilize a YAML file to store event data for easy management and retrieval.
- Implement functionality to read event data from the YAML file and display it on the events page.
- Enhance the user interface to ensure intuitive navigation and interaction with event information.
- Ensure compatibility and responsiveness across different devices and screen sizes.

## Expected Outcome
- Users will have access to a visually appealing and interactive events page.
- Event information will be displayed in a clear and organized manner, improving user experience.
- The integration of the FullCalendar plugin will add functionality such as calendar views in list/month/week/day.
- Maintainers can easily manage and update event data through the YAML file.

## Additional Information
- The NukeHub events page (https://nukehub.org/events/) serves as a reference for implementing similar features.

**Comment by ahnaf-tahmid-chowdhury** [comment]
YAML file used in NukeHub for event data can be found [here](https://github.com/nukehub-dev/nukehub.org/blob/main/_data/events.yml).

**Comment by ahnaf-tahmid-chowdhury** [comment]
Thank you for informing me. In that case, I will close the issue as not planned.

**Comment by MicahGale** [comment]
I know this is closed but I just wanted to add my two cents, if there is a need in the future. I think it's not worth reinventing the wheel. In this it would be best to make a public Google, Outlook, etc. calendar, and then embed it. Then the whole UI of updating the calendar, and rendering it is out of our hands.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I agree with your point, @MicahGale! There are some plugins available for [FullCalendar](https://fullcalendar.io/) that also offer support for integrating Google and Microsoft Calendar APIs, which are easy to implement. Actually, I'm not a big fan of Google/Microsoft; thus, I have considered storing them in the repository, allows us to have more control over the process and ensures that we're not dependent on third-party services.
