### ISSUE TITLE
Broken link under Research Skills

### ISSUE THREAD

**Issue by lewisgross1296** [cnerg/cnerg.github.com#240]
Under the [Research Skills](https://cnerg.github.io/community/manual/skills.html) page, the [Keeping Current in the literature](https://researchguides.library.wisc.edu/keepingcurrent) is broken.

**Comment by gonuke** [comment]
It could be replace by this one, unless someone has a better ideas: https://www.library.wisc.edu/steenbock/2023/09/08/keeping-current/

**Comment by MicahGale** [comment]
Looks like we could have GHA check for broken links: https://www.supertechcrew.com/jekyll-check-for-broken-links/

**Comment by lewisgross1296** [comment]
I still never figured out why my local jekyll was not working, so I'm not confident I can implement this or test it, but this seems like a good feature @MicahGale. Could do a quick PR to update to Paul's link and another to add jekyll link checking. Seems like this link checking would be good for every link, not just this one

**Comment by MicahGale** [comment]
I am getting ready to travel, so now's not a great time for me to do this.
