### ISSUE TITLE
Host from a custom domain?

### ISSUE THREAD

**Issue by MicahGale** [cnerg/cnerg.github.com#263]
Something like:
* cnerg.wisc.edu
* cnerg.org

Could look a little more professional. I don't know what the university policy on subdomains is. Given the NEEP website I imagine it's not straight forward.

Cnerg.org is available and <$20 a year. 

The process to setup pages to use a custom domain is pretty straight forward, and GH handles auto-redirects so the old `cnerg.github.io` SEO is not lost.

**Comment by gonuke** [comment]
We already host from cnerg.engr.wisc.edu

**Comment by MicahGale** [comment]
Ohh. I missed that. Is it intentional then that https://cnerg.github.io/ doesn't redirect there?

**Comment by gonuke** [comment]
It may be related to how the redirect is setup at UW.... I tried to change this in the settings and it didn't work....

**Comment by MicahGale** [comment]
You did everything I thought to, so I guess we tried.
